### ISSUE TITLE
Device Name does not update when reassigned

### ISSUE THREAD

**Issue by audioteck** [josephdadams/TallyArbiter-M5StickCListener#9]
I love that the server remembers the device assignments. the name does not seem to be updating correctly. The sticks get stuck on a name and cant be changed.n

**Comment by josephdadams** [comment]
Always something to fix... :) I will take a look

**Comment by audioteck** [comment]
Thanks so much. Super excited to get this going!

**Comment by josephdadams** [comment]
@audioteck can you try the latest commit and see if that helps? I don't have my m5 with me to test this.

**Comment by audioteck** [comment]
I will as soon as I can. Do you have a sketch for using the M5stick ATOM
Matrix? I would love to have one just show Green for Prvw and Red for Prgm.

**Comment by josephdadams** [comment]
https://github.com/josephdadams/TallyArbiter-M5AtomMatrixListener

**Comment by audioteck** [comment]
Looks like the same issue. If i switch the device the name on the M5Stick
Screen does not change. The tally function responds to the new device
assignment, just not the text on the screen. Also it seems that the wifi is
not as stable as before. When it connects it hangs on a screen rather than
going to the tally screen. When i reboot, i need to reboot a second time
for it to connect to Wifi...

**Comment by josephdadams** [comment]
Try it again. I found a bug with the recently added STATIC configuration method.

The device name seems to respond as expected for me. It shows the device name, and if I switch it to another device, it gets updated. It does look like if you change the device name in the TA server, that it won't update the clients. I can work on that.

**Comment by audioteck** [comment]
Thanks. Am I doing something wrong with GitHub. I forked your repository,
but when I open the .iso in the Arduino ide it makes me put it in a folder
and then git can't see it anymore. Sorry I'm a total coding noob.

**Comment by josephdadams** [comment]
I'm not sure how to keep it tracking with git, sorry! I do a lot of that manually.

**Comment by peterfdej** [comment]
add: 
socket.emit("devices");
after line 220.

**Comment by dakahl** [comment]
> Thanks. Am I doing something wrong with GitHub. I forked your repository, but when I open the .iso in the Arduino ide it makes me put it in a folder and then git can't see it anymore. Sorry I'm a total coding noob.

The Arduino IDE forces you to have the .ino-Project file inside a folder with the same name. So when you open the .ino-File for the first time (by double click) the Arudio IDE asks you if he should move the file inside a folder. This file is getting ignored by git, because it is listed in the .gitignore file.
**Folder and files listed in .gitignore are getting ignored by git. So just delete the line inside the .gitignore file or delete the file.**

I personally like the stucture of this repo. The original file is always stored in the root folder and can easily be updated.
For diffrent projects I just copy the file and rename it and than open it with a double click so it gets moved inside a seperate folder. I than add this folders to the .gitignore file. I this way I can easily work on diffrent projects and can always copy a clean file with the ability to update this in the future.

I fixed the problem with the wrong display name and made an pull request #17.
I will also make one on the TallyArbiter software, to improve it also there.

**Comment by josephdadams** [comment]
Thanks to @dakahl 's work, this should be fixed in the latest.
